logging:
  level:
    root: WARN
    org.springframework.web: WARN
    com.bluecc: DEBUG
    org.hibernate: WARN

server:
  port: 8088

# DataSource Config
spring:
  cloud:
    stream:
      function:
        definition: fizzBuzzProducer;fizzBuzzProcessor;fizzBuzzConsumer;printer
      bindings:
        fizzBuzzProducer-out-0:
          destination: numbers
        fizzBuzzProcessor-in-0:
          destination: numbers
        fizzBuzzProcessor-out-0:
          destination: fizz-buzz
        fizzBuzzConsumer-in-0:
          destination: fizz-buzz
        printer-in-0:
          destination: printer
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true

  datasource:
    #    dynamic:
    #      hikari:
    #        connection-test-query: SELECT 1
    #      # primary: master #设置默认的数据源或者数据源组, 默认值即为master
    #      # primary: bot
    #      primary: master
    #      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
    #        datasource:
    #            master:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_proto?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
    username: "root"
    password: "root"
    hikari:
      max-pool-size: 10
      min-idle: 5

# 业务日期
mock.date: 2020-12-21

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
  webapp:
    index-redirect-enabled: true
